# Form implementation generated from reading ui file 'OCRWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import image_categorisation_powered_by_OCR as imgc


class Ui_OCRWindow(object):
    def backToCategorise(self,main_w,OCRWindow):
        main_w.show()
        OCRWindow.hide()
        
    def ocrImage(self):
       imgc.os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = self.txtGoogleCredential_2.text()
       OCRResult = "\n".join([str(x) for x in imgc.comparison.detect_text(self.txtImage.text())])
       print(OCRResult)
       self.txtAOCRResult.setText(OCRResult)
        
    def setupUi(self, OCRWindow, MainWindow):
        MainWindow.hide()
        OCRWindow.setObjectName("OCRWindow")
        OCRWindow.resize(1078, 350)
        OCRWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(OCRWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 1061, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.txtGoogleCredential_2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtGoogleCredential_2.setFont(font)
        self.txtGoogleCredential_2.setObjectName("txtGoogleCredential_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtGoogleCredential_2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.txtImage = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtImage.setFont(font)
        self.txtImage.setObjectName("txtImage")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtImage)
        self.btnBack = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.backToCategorise(MainWindow,OCRWindow))
        self.btnBack.setGeometry(QtCore.QRect(880, 140, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnBack.setFont(font)
        self.btnBack.setObjectName("btnBack")
        self.txtAOCRResult = QtWidgets.QTextEdit(self.centralwidget)
        self.txtAOCRResult.setGeometry(QtCore.QRect(10, 140, 831, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtAOCRResult.setFont(font)
        self.txtAOCRResult.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.txtAOCRResult.setObjectName("txtAOCRResult")
        self.btnOCR = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.ocrImage())
        self.btnOCR.setGeometry(QtCore.QRect(880, 230, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnOCR.setFont(font)
        self.btnOCR.setObjectName("btnOCR")
        OCRWindow.setCentralWidget(self.centralwidget)
        
        self.retranslateUi(OCRWindow)
        QtCore.QMetaObject.connectSlotsByName(OCRWindow)

    def retranslateUi(self, OCRWindow):
        _translate = QtCore.QCoreApplication.translate
        OCRWindow.setWindowTitle(_translate("OCRWindow", "OCR Window"))
        self.label_7.setText(_translate("OCRWindow", "Google Credential json file path"))
        self.txtGoogleCredential_2.setPlaceholderText(_translate("OCRWindow", "File path to google credential json file"))
        self.label_8.setText(_translate("OCRWindow", "Image path"))
        self.txtImage.setPlaceholderText(_translate("OCRWindow", "Path to image for OCR"))
        self.btnBack.setText(_translate("OCRWindow", "Back"))
        self.btnOCR.setText(_translate("OCRWindow", "OCR"))

    
        
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OCRWindow = QtWidgets.QMainWindow()
    ui = Ui_OCRWindow()
    ui.setupUi(OCRWindow)
    OCRWindow.show()
    sys.exit(app.exec())
